modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"

[[mods]]
modId = "templatemod"
version = "${version}"
description = ""

[[dependencies.templatemod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.templatemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.templatemod]]
modId = "architectury"
mandatory = true
versionRange = "[4.11,)"
ordering = "AFTER"
side = "BOTH"
